= メモ帳

== ロジックメモ（リスト型）

=== 宣言

プロトタイプ宣言::
[source,c]
----
typedef struct list_name
{
    type elem;
    ListName* prev;
    ListName* next;
} ListName;
----

変数宣言::
[source,c]
----
ListName* ver_name = NULL;
----

=== 初期化

[source,c]
----
ListName* get_new(type elem)
{
    ListName* new_list = (ListName*)malloc(sizeof(ListName));
    new_list->elem = elem;
    new_list->next = NULL;
    new_list->prev = NULL;
    return new_list;
}
----

=== 要素移動

最初::
[source,c]
----
ListName* get_first(ListName* list_)
{
    if (list_ == NULL)
    {
        return NULL;
    }
    while(list_->prev != NULL)
    {
        list_ = list_->prev;
    }
    return list_
}
----

最後::
[source,c]
----
ListName* get_last(ListName* list_)
{
    if (list_ == NULL)
    {
        return NULL;
    }
    while(list_->next != NULL)
    {
        list_ = list_->next;
    }
    return list_
}
----

ランダムアクセス::
[source,c]
----
ListName* get_at(ListName* list_, int index)
{
    if (list_ == NULL)
    {
        return NULL;
    }
    list_ = get_first(list_);
    int i;
    for (i = 0; i < index; i++)
    {
        list_ = list_->next;
    }
    return list_
}
----

=== 追加

ユニバーサル(前方挿入)::
[source,c]
----
void prepend(ListName* list_, type elem)
{
    if(list_ == NULL)
    {
        list_ = get_new(elem);
    }
    else
    {
        ListName* new_list = get_new(elem);
        new_list->next = list_;
        new_list->prev = list_->prev;
        if (list->prev != NULL)
        {
            list_->prev->next = new_list;
        }
        list_->prev = new_list;
    }
}
----

ユニバーサル(後方挿入)::
[source,c]
----
void append(ListName* list_, type elem)
{
    if (list_ == NULL)
    {
        list_ = get_new(elem);
    }
    else
    {
        ListName* new_list = get_new(elem);
        new_list->prev = list_;
        new_list->next = list_->next;
        if (list->next != NULL)
        {
            list_->next->prev = new_list;
        }
        list_->next = new_list;
    }
}
----

先頭::
[source,c]
----
void append_at_last(ListName* list_, type elem)
{
    prepend(get_first(list_), elem);
}
----

末尾::
[source,c]
----
void append_at_last(ListName* list_, type elem)
{
    append(get_last(list_), elem);
}
----

ランダム(前方)::
[source,c]
----
void prepend_at(ListName* list_, int index, type elem)
{
    prepend(get_at(list_, index), elem);
}
----

ランダム(後方)::
[source,c]
----
void append_at(ListName* list_, int index, type elem)
{
    append(get_at(list_, index), elem);
}
----


=== 削除

単体::
[source,c]
----
void delete(ListNale* list_)
{
    if (list_ != NULL)
    {
        if (list_->prev != NULL && list_->next != NULL)
        {
            list_->prev->next = list_->next;
            list_->next->prev = list_->prev;
        }
        else if (list_->prev == NULL && list_->next != NULL)
        {
            list_->next->prev = NULL;
        }
        else if (list_->prev != NULL && list_->next == NULL)
        {
            list_->prev->next = NULL;
        }
        free(list_);
    }
}
----

指定::
[source,c]
----
void delete_at(ListName* list_, int index)
{
    delete(get_at(list_, index));
}
----

末尾::
[source,c]
----
void pop(ListName* list_)
{
    delete(get_last(list_));
}
----

先頭::
[source,c]
----
void pop_left(ListName* list_)
{
    delete(get_first(list_));
}
----


全体::
[source,c]
----
void delete_all(ListName* list_)
{
    if (list_ != NULL)
    {
        list_ = get_first(list_);
        ListName* next;
        do
        {
            next = list_->next;
            free(list_);
            list_ = next;
        } while(list_ != NULL);
    }
}
----


== トランプのビット表現（案）

=== 前提条件

* スートは4種類
* カードはスート毎に13枚（1〜13）
* ジョーカーもいる

=== ビット表現

汎用表現::
``NNNNNNNNNNNNNSSS`` +
ここで、Nは数字部を表すビット、Sはスート(ジョーカー含む)を表すビット

ゲーム的な意味合い::
汎用表現にもあるように、カードは下位3ビットのスートビットと、上位13ビットの数字ビットの組み合わせで表現される +
数字ビットについては、数字nを表す場合、数字部のビット列のうち下位からnビット目を1にすることで表現される +
スートビットについては、3ビットうち、1-2ビット目で通常スートを割り当て、3ビット目は特殊スート(ジョーカー)を割り当てる +
ここで、スートビットを下記のように割り当てる
::
* ジョーカー：100
* スペード：000
* クラブ：001
* ハート：010
* ダイヤ：011
::
このとき、各カードは下記のように表現される
::
* スペードのエース：``0000000000001000``
* ハートの3：``0000000000100010``

利点::
数字を数値ではなくビットで表すことによって、以下の利点が得られる
::
. 1つのビット列でカードとスートの組み合わせを表現できる
. 1つのビット列で同じスートの複数のカード番号のセットが表現できる（ただし1枚ずつ） +
(例) ハートの奇数：``1010101010101010``
. カードに対する操作がビット演算で完結する（四則演算・数値比較・スート比較・過不足判定） +
(例) ダイヤのデッキから9だけ捨てる： ``(1111111111111011) & ~( (1<<(9-1+3) )`` +
``　　1111111111111011`` +
``＆　1111011111111111`` +
``---------------------`` +
``　　1111011111111011`` +

=== 機能とビット演算

数値ビット変換::
cardを数値ビットに変換する +
``card >> 3``

数値変換::
cardを数値に変換する +
``(card >> 3) ``

スート変換::
cardをスートに変換する +
``(card << 13) >> 13``

